<form action="form" class="form">
    <h2 class="form__h2">formulaire</h2>
    <ul class="form__ul">
        <li class="form__li">
            <input class="form__input" type="email" placeholder="Adresse Email">
        </li>
        <li class="form__li">
            <input class="form__input" type="text" placeholder="Nom">
        </li>
        <li class="form__li">
            <input class="form__input" type="text" placeholder="Prénom">
        </li>
        <li class="form__li">
            <input class="form__input" type="text" placeholder="Tél">
        </li>
    </ul>

    <input class="form__btn" type="submit" value="Valider">

</form>