<li class="product__li">Taille : 
    <select name="Taille" class="product__select">
        {{here1}}
    </select>
</li>

<li class="product__li">Couleur : 
    <select name="Couleur" class="product__select">
        {{here2}}
    </select>
</li>

<li class="product__li">{{optionname}} : 
    <select name="{{optionname}}" class="product__select">
        {{here3}}
    </select>
</li>