<article class="productcard--soon">

    <section class="productcard__banner1">
        Temporairement indisponible
    </section>

    <section class="productcard__banner2">
        Bientôt épuisé
    </section>

    <section class="productcard__figure">
        <img src="{{src}}" alt="image de {{productname}}">
    </section>

    <section class="productcard__figcaption">
        <section class="productcard__desc">
            <h2 class="productcard__title">{{productname}}</h2>
            <p class="productcard__price">{{productprice}}</p>
        </section>

        <button data-id="{{id}}" class="productcard__btn">
            voir le produit
        </button>
    </section>

</article>