<article class="product--expired">

        <section class="product__visual">

            <section class="product__figure">
                <img src="{{src}}" alt="image du produit">
            </section>
    
            <section class="product__figcaption">

                <section class="product__banner1">
                    Temporairement indisponible
                </section>
        
                <section class="product__banner2">
                    Bientôt épuisé
                </section>

                <h2 class="product__title">{{productname}}</h2>
                <p class="product__price">{{price}}</p>

                <ul class="product__ul">
                    <li class="product__li">Taille : 
                        <select name="taille" class="product__select">

                        </select>
                    </li>

                    <li class="product__li">Pédallier : 
                        <select name="pedallier" class="product__select">

                        </select>
                    </li>

                    <li class="product__li">Couleur : 
                        <select name="taille" class="product__select">

                        </select>
                    </li>
                </ul>

                <section class="product__down">

                    <p class="product__desc">
                        {productdesc}
                    </p>
        
                    <button class="product__btn">
                        ajouter au panier
                    </button>
        
                </section>

            </section>
        </section>

    </article>