<nav class="navigation">
        <section class="nav__section_black">
            <div class="nav__section_black__info">
                <ul class="list">
                    <li class="list__item"><img class="list__item_img" src="assets/vector1.svg" alt="Svg localisation"></li>
                    <li class="list__item"><p class="list__item_content">62 RUE PHILIPPE LEBON - LIMOGES</p></li>
                </ul>
                <ul class="list">
                    <li class="list__item"><img class="list__item_img" src="assets/vector2.svg" alt="Svg téléphone"></li>
                    <li class="list__item"><p class="list__item_content">+33 5 55 08 26 92</p></li>
                </ul>
            </div>

            <a class="nav__section_black__register">Créer un compte</a>
        </section>

        <section class="nav__section">
            <button class="btn-menu">
                <span class="btn-menu__bar"></span>
            </button>

            <img src="assets/logo.png" alt="Logo de l'entreprise" class="nav__section_image">

            <ul class="list-links notactive">
                <li class="list__item"><a href="#" class="list__item_link">Accueil</a></li>
                <li class="list__item"><a href="#" class="list__item_link">Panier</a></li>
            </ul>

            <ul class="list__profil">
                <li class="list__item__prfl"><p class="list__item__prfl_name">{{username}}</p></li>
                <li class="list__item__prfl"><img class="list__item__prfl_img" src="https://picsum.photos/200/300" alt="Image de profil de l'utilisateur"></li>
            </ul>
        </section>
    </nav>