<article class="product__article">
        <section class="product__section">
            <p class="product__section_date">{{date}}</p>
            
            <p class="product__section_trait">|</p>
            
            <div class="product__section_content">
                
            </div>
            <p class="product__section_trait">|</p>
            
            <p class="product__section_price">price €</p>
            
            <p class="product__section_status">En cours</p>
        </section>
    </article>