<article class="productpanier">


        <section class="productpanier__figure">
            <img src="{{src}}" alt="image du produit">
        </section>

        <section class="productpanier__figcaption">

            <section class="productpanier__desc">
                <h2 class="productpanier__title">{{productname}}</h2>
                <ul class="productpanier__ul">
                    <li class="productpanier__li">Taille : Variable PHP</li>
    
                    <li class="productpanier__li">Pédallier : Variable PHP</li>
    
                    <li class="productpanier__li">Couleur : Variable PHP</li>
                </ul>
            </section>


        </section>

        <section class="productpanier__quantity">
            <p class="productpanier__x">x13</p>
            <section class="productpanier__btn">
                <button class="productpanier__plus">
                    +
                </button>
                <button class="productpanier__minus">
                    -
                </button>
            </section>
        </section>

        <section class="productpanier__price">
            <p>Prix total</p>
        </section>

    </article>