<article class="productcard--soon">

    <section class="productcard__banner1">
        Temporairement indisponible
    </section>

    <section class="productcard__banner2">
        Bientôt épuisé
    </section>

    <section class="productcard__figure">
        <img src="assets/velo.jpg" alt="image du vélo Propel Advanced SL 0">
    </section>

    <section class="productcard__figcaption">
        <section class="productcard__desc">
            <h2 class="productcard__title">Propel Advanced SL 0</h2>
            <p class="productcard__price">12 000€</p>
        </section>

        <button class="productcard__btn">
            voir le produit
        </button>
    </section>

</article>