<figure class="profil__figure">
        <img src="https://picsum.photos/200/300" alt="Image Profil Utilisateur" class="profil__figure_img">

        <figcaption class="profil__figure_content">
            <h4 class="profil__figure_content_name">{{username}}</h4>
            <p class="profil__figure_content_mail">{{mail}}</p>
            <p class="profil__figure_content_tel">{{phone}}</p>
        </figcaption>
    </figure>